apiVersion:  apps/v1
kind: Deployment
metadata:
  name: openshift-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openshift-app
  template:
    metadata:
      labels:
        app: openshift-app
    spec:
      containers:
        - name: openshift-app
          image: quay.io/ubiowororuki/openshift-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: "production"
            - name: APP_DEBUG
              value: "false"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "200Mi"
              cpu: "200m"
         