name: OpenShift CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: ubiowororuki-dev

  APP_NAME: openshift-app
  IMAGE_TAG: latest

  IMAGE_REGISTRY: quay.io
  IMAGE_NAMESPACE: ubiowororuki
  IMAGE_FULL: quay.io/ubiowororuki/openshift-app:latest

  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
  QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

# =========================
# 🔵 STAGE 1: SCAN
# =========================
jobs:

  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          path: ecommerce-app
          severity: HIGH,CRITICAL
          exit-code: 1

# =========================
# 🟢 STAGE 2: BUILD + DEPLOY
# =========================
  build-deploy:
    runs-on: ubuntu-latest
    needs: scan

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      # -------------------------
      # 🐳 Docker Setup
      # -------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # -------------------------
      # 🔐 LOGIN TO QUAY
      # -------------------------
      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ env.QUAY_USERNAME }}
          password: ${{ env.QUAY_TOKEN }}



      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_FULL }}
          severity: HIGH,CRITICAL
          exit-code: 1

      # -------------------------
      # 🔨 BUILD + PUSH IMAGE
      # -------------------------
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: ecommerce-app
          file: ecommerce-app/Dockerfile
          push: true
          tags: ${{ env.IMAGE_FULL }}

      # -------------------------
      # 🧪 IMAGE SCAN
      # -------------------------
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_FULL }}
          severity: HIGH,CRITICAL
          exit-code: 1

      # -------------------------
      # 🔧 INSTALL OC CLI
      # -------------------------
      - name: Install OpenShift CLI
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4

      # -------------------------
      # 🔐 LOGIN OPENSHIFT
      # -------------------------
      - name: Login to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      # -------------------------
      # 🚀 DEPLOY
      # -------------------------
      - name: Apply Kubernetes/OpenShift manifests
        run: |
          oc apply -f openshift/deployment.yaml
          oc apply -f openshift/service.yaml
          oc apply -f openshift/route.yaml

      # -------------------------
      # 🔄 UPDATE IMAGE
      # -------------------------
      - name: Update Deployment Image
        run: |
          oc set image deployment/${APP_NAME} \
            ${APP_NAME}=${IMAGE_FULL}

      # -------------------------
      # 📊 ROLLOUT STATUS
      # -------------------------
      - name: Rollout Status
        run: |
          oc rollout status deployment/${APP_NAME}

      # -------------------------
      # 🌐 GET ROUTE
      # -------------------------
      - name: Get Application URL
        run: |
          echo "App URL:"
          oc get route ${APP_NAME} -o jsonpath='{.spec.host}'


  docker_push_image:
    runs-on: ubuntu-latest
    needs: scan

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: ecommerce-app
          file: ecommerce-app/Dockerfile
          push: true
          tags: ${{ env.IMAGE_FULL }}