
name: OpenShift CI/CD Pipeline (Secure 3-Stage) for. openshift deployment

on:
  push:
    branches: [main]

env:
  APP_NAME: openshift-app
  IMAGE_TAG: latest
  NAMESPACE: ubiowororuki-dev

  QUAY_USERNAME: ubiowororuki
  QUAY_IMAGE: quay.io/ubiowororuki/openshift-app:latest
  DOCKER_IMAGE: docker.io/${{ secrets.DOCKER_USERNAME }}/openshift-app:latest

jobs:

  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          path: ecommerce-app
          severity: HIGH,CRITICAL
          exit-code: 1

  build:
    runs-on: ubuntu-latest
    needs: scan

    steps:
      - uses: actions/checkout@v4

     
      -  name: Set up Node.js
         uses: actions/setup-node@v4
         with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'ecommerce-app/package-lock.json'


     
      - name: Install Dependencies
        run: |
          cd ecommerce-app
          npm install

      - name: Build React App
        run: |
          cd ecommerce-app
          npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.ROBOT_USERNAME }}
          password: ${{ secrets.ROBOT_TOKEN }}

      

      
      - name: Build and Push Images
        uses: docker/build-push-action@v5
        with:
          context: ecommerce-app
          file: ecommerce-app/Dockerfile
          push: false
          load: true
          tags: |
            ${{ env.QUAY_IMAGE }}
            ${{ env.DOCKER_IMAGE }}


      - name: Push Image to Registries
        run: |
          docker tag ${{ env.QUAY_IMAGE }} quay.io/${{ env.QUAY_USERNAME }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}
          docker tag ${{ env.DOCKER_IMAGE }} docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}

          docker push quay.io/${{ env.QUAY_USERNAME }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}



      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.QUAY_IMAGE }}
          severity: HIGH,CRITICAL
          exit-code: 1


      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_IMAGE }}
          severity: HIGH,CRITICAL
          exit-code: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenShift CLI
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4

      - name: Login to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ env.NAMESPACE }}
          insecure_skip_tls_verify: true

      - name: Apply Manifests
        run: |
          oc apply -f openshift/

      - name: Update Image
        run: |
          oc set image deployment/${{ env.APP_NAME }} \
          ${{ env.APP_NAME }}=${{ env.QUAY_IMAGE }}

      - name: Rollout
        run: oc rollout status deployment/${{ env.APP_NAME }}

      - name: Check Pods
        run: oc get pods -o wide

    
      

  
    





     

    
      

  
     

  